# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build, test and deploy ASP.NET Core app to Azure Web App - biblioteca-aurea

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-and-publish:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore Biblioteca.sln

      - name: Build
        run: dotnet build Biblioteca.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Biblioteca.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish Biblioteca.Web/Biblioteca.Web.csproj --configuration Release --no-build --output "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build-test-and-publish

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1C0FDBE0D66F470D8193FD41605C84AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD46B32A9D6C48AEB77BA2C24DB70E9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4B5132998E64914B290A23E6AC72214 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "biblioteca-aurea"
          slot-name: "Production"
          package: .
